name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:21
          apps: sbt
      - name: Run sbt fmt check
        run: sbt fmt check
